version: 0.2

phases:
  install:
    commands:
      - yum -y install aws-cli
      
  build:
    commands:
      - DATABASE_ROOT_PASSWORD=$(aws ssm get-parameter --name ${ENV_PREFIX}DATABASE-MASTER-PASSWORD --with-decryption --query 'Parameter.Value' --output text)
      - sed -i s/SED_REPLACE_PASS/$DATABASE_ROOT_PASSWORD/g Templates/edx-provision-configuration.json

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
